version: '3.5'
services:
  api1:
    image: tagliatti/rinha-de-backend-2023-q3-dotnet
    hostname: api1
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Postgres=Host=db;Port=5432;Database=rinha-backend;Username=rinha-backend;Password=rinha-backend
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api2:
    image: tagliatti/rinha-de-backend-2023-q3-dotnet
    hostname: api2
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Postgres=Host=db;Port=5432;Database=rinha-backend;Username=rinha-backend;Password=rinha-backend
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  nginx:
    image: nginx:latest
    volumes:
      - ./resources/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: rinha-backend
      POSTGRES_PASSWORD: rinha-backend
      POSTGRES_DB: rinha-backend
    volumes:
      - ./resources/database.sql:/docker-entrypoint-initdb.d/database.sql
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
          
networks:
  default:
    driver: bridge
    name: rinha